server:
  port: 8888

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

lingframe:
  enabled: true
  dev-mode: true
  preload-api-jars:
    - lingframe-examples/lingframe-example-order-api
  plugin-home: plugins
  plugin-roots:
    - lingframe-examples/lingframe-example-plugin-order
    - lingframe-examples/lingframe-example-plugin-user
  host-governance:
    enabled: false
    govern-internal-calls: true
    check-permissions: true
  dashboard:
    enabled: true

